env:
  browser: false
  es2021: true
  "jest/globals": true
extends:
  - airbnb
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
  - jest
settings:
  import/resolver:
    node:
      moduleDirectory: ["node_modules", "src/"]
rules: {
  "prettier/prettier": "error",
  "no-use-before-define": [0],
  "no-unused-vars": ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }]
}
